# Generated by Django 5.1.7 on 2025-03-09 06:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetapp', '0002_recurringtransaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
