# Generated by Django 5.1.7 on 2025-03-09 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgetapp', '0003_budget_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='start_date',
        ),
    ]
