# Generated by Django 5.1.7 on 2025-03-09 12:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetapp', '0004_remove_budget_start_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='is_variable',
            field=models.BooleanField(default=False, help_text='Whether this income source varies from period to period'),
        ),
        migrations.AlterField(
            model_name='income',
            name='frequency',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('fortnightly', 'Fortnightly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('variable', 'Variable')], max_length=20),
        ),
        migrations.CreateModel(
            name='IncomeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=255)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('income', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_transactions', to='budgetapp.income')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
