# Generated by Django 5.1.7 on 2025-03-09 13:37

import datetime
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetapp', '0005_income_is_variable_alter_income_frequency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='budget',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='frequency',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('fortnightly', 'Fortnightly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='budget',
            name='rollover',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='income',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='frequency',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('fortnightly', 'Fortnightly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('variable', 'Variable')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='income',
            name='is_variable',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='income',
            name='source',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='incometransaction',
            name='date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='recurringtransaction',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='recurringtransaction',
            name='end_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='recurringtransaction',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('fortnightly', 'Fortnightly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='recurringtransaction',
            name='start_date',
            field=models.DateField(db_index=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['user', 'category'], name='budgetapp_b_user_id_15b7f4_idx'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['user', 'frequency'], name='budgetapp_b_user_id_75f25d_idx'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['user', 'created_at'], name='budgetapp_b_user_id_213940_idx'),
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['user', 'source'], name='budgetapp_i_user_id_3d451c_idx'),
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['user', 'frequency'], name='budgetapp_i_user_id_5a5c6e_idx'),
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['user', 'is_variable'], name='budgetapp_i_user_id_29bb30_idx'),
        ),
        migrations.AddIndex(
            model_name='incometransaction',
            index=models.Index(fields=['user', 'date'], name='budgetapp_i_user_id_9a2550_idx'),
        ),
        migrations.AddIndex(
            model_name='incometransaction',
            index=models.Index(fields=['income', 'date'], name='budgetapp_i_income__f9a560_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringtransaction',
            index=models.Index(fields=['user', 'budget'], name='budgetapp_r_user_id_68f1a3_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringtransaction',
            index=models.Index(fields=['user', 'active'], name='budgetapp_r_user_id_cdac1d_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringtransaction',
            index=models.Index(fields=['user', 'start_date'], name='budgetapp_r_user_id_2a4c64_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'date'], name='budgetapp_t_user_id_0215c8_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['budget', 'date'], name='budgetapp_t_budget__1a21ae_idx'),
        ),
    ]
