# Generated by Django 5.1.8 on 2025-04-16 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetapp', '0008_budget_avg_weekly_spent_budget_historical_periods_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('budget_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_spent', models.DecimalField(decimal_places=2, max_digits=12)),
                ('difference', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_current', models.BooleanField(default=False)),
                ('is_over_budget', models.BooleanField(default=False)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='budgetapp.budget')),
            ],
            options={
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['budget', 'start_date'], name='budgetapp_b_budget__0b6a72_idx')],
            },
        ),
    ]
